name: aschat
description: Chat app for friends
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.19.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_messaging: ^15.2.5
  cupertino_icons: ^1.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true